//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lmpessoa.Timer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lmpessoa.Timer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink after timer ends.
        /// </summary>
        public static string blink {
            get {
                return ResourceManager.GetString("blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Display.
        /// </summary>
        public static string display_title {
            get {
                return ResourceManager.GetString("display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hours is too big to display..
        /// </summary>
        public static string hours_too_big {
            get {
                return ResourceManager.GetString("hours_too_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Settings.
        /// </summary>
        public static string main_title {
            get {
                return ResourceManager.GetString("main_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of minutes is too big to display. Switch to using hours and try again..
        /// </summary>
        public static string minutes_too_big {
            get {
                return ResourceManager.GetString("minutes_too_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue counting after timer ends.
        /// </summary>
        public static string negative {
            get {
                return ResourceManager.GetString("negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid time..
        /// </summary>
        public static string no_valid_time {
            get {
                return ResourceManager.GetString("no_valid_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final alert after.
        /// </summary>
        public static string red_alert {
            get {
                return ResourceManager.GetString("red_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Timer.
        /// </summary>
        public static string set_timer {
            get {
                return ResourceManager.GetString("set_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds during alerts.
        /// </summary>
        public static string sounds {
            get {
                return ResourceManager.GetString("sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of timer.
        /// </summary>
        public static string timer_value {
            get {
                return ResourceManager.GetString("timer_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string use {
            get {
                return ResourceManager.GetString("use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First alert after.
        /// </summary>
        public static string yellow_alert {
            get {
                return ResourceManager.GetString("yellow_alert", resourceCulture);
            }
        }
    }
}
